### ISSUE TITLE
Month doesn't equal itself when one is a result of adding or subtracting to a month before, but only in Node.js

### ISSUE THREAD

**Issue by rsstiglitz** [fullcalendar/temporal-polyfill#21]
![Bildschirmfoto 2023-11-15 um 17 58 00](https://github.com/fullcalendar/temporal/assets/103580548/c0d3eef0-79fa-4723-aadc-1feaa024feea)

This might be a Node bug, running the same code in Chrome DevTools for example yields true.

Months which are a result of going forward are fine:

```js
const monthAfter1 = Temporal.PlainYearMonth.from({year: 2022, month 11}).add({month: 1});
const monthAfter2 = Temporal.PlainYearMonth.from({year: 2022, month 11}).subtract({month: -1});

monthAfter1.equals(Temporal.PlainYearMonth.from({year: 2022, month 12})) // true
monthAfter2.equals(Temporal.PlainYearMonth.from({year: 2022, month 12})) // true
```

while going backwards breaks `equals`:

```js
const monthAfter1 = Temporal.PlainYearMonth.from({year: 2022, month 11}).add({month: -1});
const monthAfter2 = Temporal.PlainYearMonth.from({year: 2022, month 11}).subtract({month: 1});

monthAfter1.equals(Temporal.PlainYearMonth.from({year: 2022, month 10})) // false
monthAfter2.equals(Temporal.PlainYearMonth.from({year: 2022, month 10})) // false
```

Sorry this isn't more detailed, already wasted 2 hours on this nasty bug and now I'm tired. 😝

**Comment by rsstiglitz** [comment]
This code right here seems to be the culprit, I'm not sure though: https://github.com/fullcalendar/temporal/blob/8ddf7a709375bf1586587512968094daaa525f43/packages/temporal-polyfill/src/public/plainYearMonth.ts#L189C1-L193C5

The "official" docs state:

> The overflow option has no effect in the default ISO 8601 calendar, because a year is always 12 months and therefore not ambiguous. It doesn't matter in this case that years and months can be different numbers of days, **as the resolution of Temporal.PlainYearMonth does not distinguish days**. However, overflow may have an effect in other calendars where years can be different numbers of months.

So it's probably not a good idea to convert the month to a `PlainDate` and to use `daysInMonth` internally.

**Comment by leonadler** [comment]
@arshaw Would you like/merge a PR for this, or do you prefer I retest it after _one refactor to rule them all_ is finished?

**Comment by arshaw** [comment]
This is now fixed in [v0.2.0](https://github.com/fullcalendar/temporal-polyfill/releases/tag/v0.2.0). Please confirm when you have a chance. Thanks all!

**Comment by rsstiglitz** [comment]
Thank you for the release! Was anyone able to find out why or reproduce if this was not an issue in browsers, only in Node.js, like I stated in the OP? Even if this is fixed now, I would still be very very interested how that could've happened...

**Comment by arshaw** [comment]
@rsstiglitz I'd be very curious to know myself! However I don't think I have the bandwidth right now to spin up the old code for debugging. I can't think of an obvious culprit, so this might remain a mystery.
