### ISSUE TITLE
Class constructor DateTimeFormat cannot be invoked without 'new'

### ISSUE THREAD

**Issue by digaus** [fullcalendar/temporal-polyfill#25]
When using this polyfill with `any-date-parser` I get this error.

Browser allows creation of DateTimeFormat without `new` but this polyfill does not.

Is this according to spec or should I post this issue on `any-date-parser` ?

Edit: According to MDN docs it should be possible without `new`
![image](https://github.com/fullcalendar/temporal-polyfill/assets/15358538/2f9fc29d-9810-482a-b6e2-cb04ba65dee5)

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat#return_value

**Comment by arshaw** [comment]
This is fixed in [v0.2.1](https://github.com/fullcalendar/temporal-polyfill/releases/tag/v0.2.1)

@digaus please write back here if any further problems with `Intl.DateTimeFormat` and `new`

**Comment by digaus** [comment]
Looking good, thanks for the fast fix :)
