### ISSUE TITLE
Wrong export in types for `DateTimeFormat`

### ISSUE THREAD

**Issue by Ayc0** [fullcalendar/temporal-polyfill#28]
In `impl.esm.js`, we export `DateTimeFormat`, `Temporal`, and `toTemporalInstant`:

<img width="789" alt="image" src="https://github.com/fullcalendar/temporal-polyfill/assets/22725671/e70760e1-3e31-4092-9c47-30bbe32b8f57">

But in `index.d.ts`, we re-export from `temporal-spec`
<img width="430" alt="image" src="https://github.com/fullcalendar/temporal-polyfill/assets/22725671/0d3839b9-c695-4be2-a293-c6c03ac27f16">

which exports `Temporal`, `Intl`, and `toTemporalInstant`

<img width="516" alt="image" src="https://github.com/fullcalendar/temporal-polyfill/assets/22725671/e9923aaa-9a64-4f26-ac19-28e2b7de2c61">

So according to the types, we should be using `Intl.DateTimeFormat` and not `DateTimeFormat` which is not accurate

**Comment by arshaw** [comment]
You are very right. I'll fix this for the next release.

**Comment by arshaw** [comment]
This has been fixed and released in [v0.2.2](https://github.com/fullcalendar/temporal-polyfill/releases/tag/v0.2.2). Thank you for the report.
