### ISSUE TITLE
Vite support

### ISSUE THREAD

**Issue by JonathonRP** [fullcalendar/temporal-polyfill#38]
Is this supported in vite? Getting undefined Temporal and ect. Importing global.

**Comment by arshaw** [comment]
@JonathonRP, do you have a "main" file that initializes the root component? The `'temporal-polyfill/global'` import should go at the top of that file. I bet your error is occurring because the temporal import is occurring after some top-level code that uses it.

**Comment by JonathonRP** [comment]
I'm using vite and sveltekit. My main top level is vite.config.ts and I tried importing from there global but that did not work and have been trying various other methods to populate vites define/vite.esbuild define also

**Comment by JonathonRP** [comment]
also noticed it uses globalThis which does that work in node?
@arshaw

**Comment by arshaw** [comment]
`globalThis` works [since Node 12](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#browser_compatibility).

`vite.config.ts` is the wrong place to import the polyfill as its a config file and does not run within the browser.
