### ISSUE TITLE
consider making Temporal.Now a class

### ISSUE THREAD

**Issue by henryw374** [fullcalendar/temporal-polyfill#44]
Hi, I would like to create drop-in alternatives to Temporal.Now, so that tests can substitute this object for alternatives that provide control over the actual time used. 

I would like to use the type information in function signatures that return Temporal.Now -like objects, but afaik can't because it is not marked as a class, but rather a 'const'.

**Comment by arshaw** [comment]
Hi @henryw374. The typescript definitions come from upstream here:
https://github.com/tc39/proposal-temporal/blob/727211d41366390c9a56a36f1009f379bd8eb4d4/polyfill/index.d.ts#L1321

However, I think you can achieve what you'd hoping by using typescript's `typeof`

```ts
import 'temporal-polyfill/global'

type NowInterface = typeof Temporal.Now

const CustomNow: NowInterface = {
  // will give type errors unless all methods implemented
}
```

**Comment by henryw374** [comment]
Perfect! Thanks
